<?php

/**
 * Implements hook_permission().
 */
function ophir_odt_import_permission() {
  return array(
    'import odt' =>  array(
      'title' => t('Import ODT files'),
      'description' => t('Allows the user to choose an ODT file to import.
      Not all users should have this permission, because this allows the user
      to output anything to the browser, which is a security concern.'),
    ),
  );
}

/**
 * Implements hook_form_node_form_alter().
 */
function ophir_odt_import_form_node_form_alter(&$form, $form_state, $form_id) {
  if (isset($form["body"]["#type"]) && $form["body"]["#type"] === "container") {
    $form['ophir_odt_import'] = array(
      '#type' => 'fieldset',
      '#title' => t('ODT file import'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#description' => t('Select a file to import. This file will be parsed and set as content body. Make sure you do not have anything in the body field while importing an ODT file, as the import will overwrite the content body'),
      '#attributes' => array('id' => 'ophir_odt_import-fieldset'),
    );
    $form['ophir_odt_import']['importfile'] = array(
      '#type' => 'file',
      '#title' => t('File to import'),
      '#size' => 50,
    );
    $form['ophir_odt_import']['#access'] = user_access('import odt');
    $form['#attributes']['enctype'] = 'multipart/form-data';
    drupal_add_js(drupal_get_path('module', 'ophir_odt_import') . '/ophir_odt_import.validate.js');
  }

}

/**
 * Implements hook_help().
 */
function node_ophir_odt_import_help($path, $arg) {
  switch ($path) {
    case 'examples/node_example':
      return "<p>" . t("The Ophir ODT Import allows you to import ODT
        files in drupal. Not all styling information are imported,
        but links, headings, quotes, and footnotes should be rendered
        correctly in drupal.
          To access the import an ODT file, just create a new page, do not
          fill the body textfield, and choose a file in <b>ODT file import</b>
        ") . "</p>";
  }
}

/**
 * Implements hook_node_validate().
 */
function ophir_odt_import_node_validate($node, $form, &$form_state) {
  if (@$_FILES['files']['tmp_name']['importfile'] && user_access('import odt')) {
	  $extensions = 'odt ';
	  $file = new stdClass();
	  $file->filename = file_munge_filename(trim(basename($_FILES['files']['name']['importfile']), '.'), $extensions);
	  $file->filemime = file_get_mimetype($file->filename);
	  if ($file->filemime !== 'application/vnd.oasis.opendocument.text') {
		  form_set_error('importfile', t('File uploaded is not a odt file'));
	  }
  }
}

/**
 * Implements hook_node_submit().
 */
function ophir_odt_import_node_submit($node, $form, &$form_state) {
  if (@$_FILES['files']['tmp_name']['importfile'] && user_access('import odt')) {
    $response = parse_odt($_FILES['files']['tmp_name']['importfile']);
    if ($response['error'] === '') {
      $node->body[LANGUAGE_NONE][0]['value'] = $response['content'];
      $node->body[LANGUAGE_NONE][0]['format'] = 'full_html';
    }
  }
}

function parse_odt($file) {
  global $_ophir_odt_import_conf;
  require_once("ophir.php");
  $_ophir_odt_import_conf["images_folder"] = "public:///";
  return array('error' => '', 'content' => odt2html($file));
}
